### ISSUE TITLE
Progress bar during Mobile ID request not displayed with Safari 7.1

### ISSUE THREAD

**Issue by FreddyKaiser** [SCS-CBU-CED-IAM/simplesaml-mobileid#51]
Can be tested with: https://cartel.ch/idp/module.php/core/authenticate.php

![simplesamlphp-safari_7 1_01](https://cloud.githubusercontent.com/assets/4628116/4403598/7923c97e-44a5-11e4-99f1-a371d0defc14.png)
![simplesamlphp-safari_7 1_02](https://cloud.githubusercontent.com/assets/4628116/4403599/7933aefc-44a5-11e4-9ac4-dbd9ff961271.png)

**Comment by michellotto** [comment]
Should be fine now also with Safari 7.1
